version: '3'
services:
  jenkins-agent:
    build:
      context: ./
      args:
        ENABLE_JENKINS_AGENT: jenkins-agent
    image: seanly/jenkins-agent:inbound
  jenkins-swarm:
    build:
      context: ./
      args:
        ENABLE_JENKINS_AGENT: swarm-client
    image: seanly/jenkins-agent:swarm
