version: '3'
services:
  jenkins-agent:
    build:
      context: ./
    image: seanly/jenkins-agent:inbound-v3
    privileged: true

  jenkins-swarm:
    image: seanly/jenkins-agent:inbound-v3
    environment:
      AGENT_SERVICE: swarm-client
      CLEANUP_PERIODIC: daily
    privileged: true
